
networks:
  ai_net:
    driver: bridge

services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/docker/ollama:/root/.ollama
    mem_limit: 3g
    cpus: 8
    networks:
      - ai_net

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - SEARX_BASE_URL=http://searxng:8081  # punta solo alla base URL
    depends_on:
      - ollama
      - searxng
    volumes:
      - ${HOME}/docker/openwebui:/app/backend/data
    mem_limit: 1g
    cpus: 2
    networks:
      - ai_net

 
  searxng:
      image: searxng/searxng:latest
      container_name: searxng
      restart: unless-stopped
      ports:
        - "8081:8081"
      environment:
        - BASE_URL=http://localhost:8081
        - SEARXNG_PORT=8081 
      volumes:
        - ${HOME}/docker/searxng:/etc/searxng
      mem_limit: 500m
      cpus: 1
      networks:
        - ai_net


